spring.application.name=library-management
# H2 in-memory database
spring.datasource.url=jdbc:h2:mem:librarydb
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Auto-create tables from your @Entity classes
spring.jpa.hibernate.ddl-auto=create-drop

# Enable the H2 browser console at localhost:8080/h2-console
spring.h2.console.enabled=true